#!/bin/bash
#iterating through multiple directories

for file in /home/system/sp/1029/.b* /home/system/sp/1029/badtest
do
if [ -d "$file" ]
then
echo "$file is a directory"
elif [ -f "$file" ]
then
echo "$file is a file"
else
echo "$file doesn't exist"
fi
done
